# Generated by Django 6.0.2 on 2026-04-13 11:22

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('finance', 'category')
    default_categories = [
        {'name': 'Groceries', 'type': 'expense', 'icon_name': 'ShoppingCart', 'is_default': True, 'user_id': None},
        {'name': 'Dining Out', 'type': 'expense', 'icon_name': 'Coffee', 'is_default': True, 'user_id': None} ,
        {'name': 'Housing & Utilities', 'type': 'expense', 'icon_name': 'Building2', 'is_default': True, 'user_id': None},
        {'name': 'Transportation', 'type': 'expense', 'icon_name': 'Bus', 'is_default': True, 'user_id': None},
        {'name': 'Health & Medical', 'type': 'expense', 'icon_name': 'ScanHeart', 'is_default': True, 'user_id': None},
        {'name': 'Subscriptions & Services', 'type': 'expense', 'icon_name': 'Pointer', 'is_default': True, 'user_id': None},
        {'name': 'Shopping & Personal Care', 'type': 'expense', 'icon_name': 'Handbag', 'is_default': True, 'user_id': None},
        {'name': 'Entertainment & Hobbies', 'type': 'expense', 'icon_name': 'Gamepad2', 'is_default': True, 'user_id': None},
        {'name': 'Other', 'type': 'expense', 'icon_name': 'Ellipsis', 'is_default': True, 'user_id': None},

        {'name': 'Salary', 'type': 'income', 'icon_name': '', 'is_default': True, 'user_id': None},
        {'name': 'Freelance & Projects', 'type': 'income', 'icon_name': '', 'is_default': True, 'user_id': None},
        {'name': 'Business Revenue', 'type': 'income', 'icon_name': '', 'is_default': True, 'user_id': None},
        {'name': 'Investments & Dividends', 'type': 'income', 'icon_name': '', 'is_default': True, 'user_id': None},
        {'name': 'Rental Income', 'type': 'income', 'icon_name': '', 'is_default': True, 'user_id': None},
        {'name': 'Gifts & Bonuses', 'type': 'income', 'icon_name': '', 'is_default': True, 'user_id': None},
        {'name': 'Cashback & Refunds', 'type': 'income', 'icon_name': '', 'is_default': True, 'user_id': None},
        {'name': 'Government & Benefits', 'type': 'income', 'icon_name': '', 'is_default': True, 'user_id': None},
        {'name': 'Other', 'type': 'income', 'icon_name': 'Ellipsis', 'is_default': True, 'user_id': None},
    ]

    for category_data in default_categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            type=category_data['type'],
            defaults={
                'icon_name': category_data['icon_name'],
                'is_default': category_data['is_default'],
                'user_id': category_data['user_id']
            })

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]