# Generated by Django 6.0.2 on 2026-05-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='financial_period',
        ),
    ]
