# Generated by Django 6.0.2 on 2026-05-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20260513_1407'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goal',
            name='unique_goal_title_per_user',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
