# Generated by Django 6.0.2 on 2026-03-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
