# Generated by Django 6.0.2 on 2026-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20260414_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='Transaction', max_length=100),
            preserve_default=False,
        ),
    ]
