# Generated by Django 6.0.2 on 2026-03-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_category_profile_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile',
            new_name='profile_picture',
        ),
    ]
