# Generated by Django 6.0.2 on 2026-04-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_icon_path_category_icon_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_cap_streak',
            new_name='focus_streak',
        ),
    ]
