# Generated by Django 6.0.2 on 2026-04-28 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_date_transactionstemplates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionsTemplates',
            new_name='Templates',
        ),
    ]
